#!/usr/bin/env python3
"""
text_spacing_preset
====================

Emit a ready-to-include CSS block for an opt-in "comfortable reading"
text-spacing toggle: line-height, letter-spacing, word-spacing, and
paragraph spacing widened to the WCAG (Web Content Accessibility
Guidelines) 1.4.12 Text Spacing minimums, applied to exactly the
elements ``lint_a11y.py``'s ``body-text-tracking-tight`` rule audits
(:data:`lint_a11y.BODY_TEXT_TAGS`: ``p``, ``li``, ``dd``,
``blockquote``, ``td``, ``figcaption``).

This is the **make-side** counterpart to that audit rule, in the same
spirit as ``sprezzature-colors/scripts/palette_to_tailwind.py`` being
the make-side counterpart of ``audit_contrast.py``: the audit flags a
page that fights readability by narrowing letter-spacing on running
text; this script emits the opposite, an explicit reader-facing toggle
a page can ship.

Why these defaults
-------------------
WCAG 1.4.12 requires that a page not lose functionality when a *user*
applies, at minimum: line-height >= 1.5x font size, spacing following
paragraphs >= 2x font size, letter-spacing >= 0.12x font size, and
word-spacing >= 0.16x font size. Those four numbers are this script's
defaults. The empirical motivation behind the *direction* (wider, not
narrower) comes from Zorzi et al. 2012: dyslexic children (8-14yo)
read 20% faster with letter-spacing roughly doubled on running text,
with no prior training (see
https://www.planetesante.ch/Magazine/Bebes-enfants-et-adolescents/Dyslexie/Dyslexie-espacer-les-lettres-permet-d-ameliorer-la-lecture).
The WCAG minimums ship as the default because they are the
interoperable, standards-defined values; every flag below can be
widened past them for a stronger preset.

Usage
-----
::

    # Default WCAG 1.4.12 minimums, toggled by [data-text-spacing="comfortable"]
    python text_spacing_preset.py

    # Wider preset, custom attribute/value, write to a file
    python text_spacing_preset.py --letter-spacing 0.16 --word-spacing 0.32 \\
        --attr data-reading-mode --value on --out reading-mode.css

Notes
-----
* Python 3.10+, stdlib only.
* Output is plain CSS, meant to be pasted into (or concatenated with)
  the project's stylesheet entry point — the same way this site's
  existing ``[data-color-scheme=dark]`` / ``[data-color-mode=corporate]``
  blocks are hand-authored in ``tailwind-input.css`` rather than
  generated by Tailwind itself.
* This script only emits CSS. Wiring an actual control that sets the
  attribute and persists the choice (in the spirit of this site's
  ``web/js/voir-pour.js`` for color-vision simulation) is left to the
  consuming project.

Author
------
`Warith HARCHAOUI, Ph.D. <https://www.linkedin.com/in/warith-harchaoui/>`_
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _argparse import make_parser  # noqa: E402
from lint_a11y import BODY_TEXT_TAGS  # noqa: E402

#: Paragraph-like block elements that get the "spacing following
#: paragraphs" rule. A subset of BODY_TEXT_TAGS: list items and table
#: cells are running text too, but WCAG 1.4.12 speaks specifically of
#: "spacing following paragraphs", not every text-bearing tag.
PARAGRAPH_TAGS: frozenset[str] = frozenset({"p", "blockquote", "dd"})


def build_css(
    *,
    attr: str = "data-text-spacing",
    value: str = "comfortable",
    line_height: float = 1.5,
    letter_spacing_em: float = 0.12,
    word_spacing_em: float = 0.16,
    paragraph_spacing_em: float = 2.0,
) -> str:
    """
    Build the opt-in text-spacing CSS block.

    Parameters
    ----------
    attr : str, default "data-text-spacing"
        Attribute name toggled on an ancestor (typically ``<html>``) to
        activate the preset.
    value : str, default "comfortable"
        Attribute value that activates the preset.
    line_height : float, default 1.5
        WCAG 1.4.12 minimum: line-height >= 1.5x the element's font size.
    letter_spacing_em : float, default 0.12
        WCAG 1.4.12 minimum, in ``em`` (already relative to font size).
    word_spacing_em : float, default 0.16
        WCAG 1.4.12 minimum, in ``em``.
    paragraph_spacing_em : float, default 2.0
        WCAG 1.4.12 minimum spacing following paragraphs, in ``em``.

    Returns
    -------
    str
        A complete, deterministic CSS block ending in a newline.
    """
    body_selector = ",\n".join(
        f'[{attr}="{value}"] {tag}' for tag in sorted(BODY_TEXT_TAGS)
    )
    paragraph_selector = ",\n".join(
        f'[{attr}="{value}"] {tag}' for tag in sorted(PARAGRAPH_TAGS)
    )
    return (
        f'/* Comfortable reading: WCAG 1.4.12 Text Spacing minimums, opt-in via\n'
        f'   [{attr}="{value}"]. Pairs with the body-text-tracking-tight audit\n'
        f'   rule in sprezzature-accessibility/scripts/lint_a11y.py. */\n'
        f"{body_selector} {{\n"
        f"  line-height: {line_height};\n"
        f"  letter-spacing: {letter_spacing_em}em;\n"
        f"  word-spacing: {word_spacing_em}em;\n"
        f"}}\n"
        f"{paragraph_selector} {{\n"
        f"  margin-bottom: {paragraph_spacing_em}em;\n"
        f"}}\n"
    )


def main() -> int:
    """CLI entry point."""
    p = make_parser(
        prog="sprezzature-accessibility-text-spacing",
        description=(
            "Emit an opt-in 'comfortable reading' CSS block (WCAG 1.4.12 Text "
            "Spacing minimums) for the elements lint_a11y.py's "
            "body-text-tracking-tight rule audits. Make-side counterpart to "
            "that audit rule."
        ),
        epilog=(
            "Examples:\n"
            "  sprezzature-accessibility-text-spacing\n"
            "  sprezzature-accessibility-text-spacing --letter-spacing 0.16 "
            "--word-spacing 0.32 --out reading-mode.css\n"
        ),
    )
    p.add_argument(
        "--attr", default="data-text-spacing",
        help="Toggle attribute name. Default: data-text-spacing.",
    )
    p.add_argument(
        "--value", default="comfortable",
        help="Toggle attribute value. Default: comfortable.",
    )
    p.add_argument(
        "--line-height", type=float, default=1.5,
        help="Default: 1.5 (WCAG 1.4.12 minimum).",
    )
    p.add_argument(
        "--letter-spacing", type=float, default=0.12,
        help="In em. Default: 0.12 (WCAG 1.4.12 minimum).",
    )
    p.add_argument(
        "--word-spacing", type=float, default=0.16,
        help="In em. Default: 0.16 (WCAG 1.4.12 minimum).",
    )
    p.add_argument(
        "--paragraph-spacing", type=float, default=2.0,
        help="In em. Default: 2.0 (WCAG 1.4.12 minimum).",
    )
    p.add_argument(
        "--out", type=Path, default=None,
        help="Write to this file instead of stdout.",
    )
    args = p.parse_args()

    css = build_css(
        attr=args.attr,
        value=args.value,
        line_height=args.line_height,
        letter_spacing_em=args.letter_spacing,
        word_spacing_em=args.word_spacing,
        paragraph_spacing_em=args.paragraph_spacing,
    )
    if args.out:
        args.out.write_text(css, encoding="utf-8")
        sys.stderr.write(f"Wrote {args.out}\n")
    else:
        sys.stdout.write(css)
    return 0


if __name__ == "__main__":
    sys.exit(main())
